name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.0.2

    - name: Set up Go
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.0
      with:
        go-version: 1.19
        check-latest: true

    - name: Build
      run: make build-all

    - name: Unit Tests
      run: make unit-test
